baseURL = 'https://sinofseven.github.io/try-hugo-page/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-book'

enableGitInfo = true

[params]
BookTheme = 'auto'
BookRepo = 'https://github.com/sinofseven/try-hugo-page'
BookSearch = false
