name: deploy-page

on:
  push:


jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: peaceiris/actions-hugo@v2
        with:
          extended: true
      - run: |
          cd hugo
          hugo --minify
          find public | sort
      - uses: actions/upload-pages-artifact@v1
        with:
          path: hugo/public/
      - uses: actions/deploy-pages@v1
